-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `workspace`;
USE SCHEMA `ecommerce`;

-- COMMAND ----------

truncate table ecommerce.ecom_gold_user_viewed;
truncate table ecommerce.ecom_gold_user_cart;

-- COMMAND ----------

SELECT count(*) from workspace.ecommerce.ecom_gold_user_viewed;
SELECT count(*) from workspace.ecommerce.ecom_gold_user_cart;

-- COMMAND ----------

DROP table ecommerce.ecom_gold_user_viewed;
DROP table ecommerce.ecom_gold_user_cart;
DROP TABLE ecommerce.ecom_bronze_events;
DROP TABLE ecommerce.ecom_silver_events

-- COMMAND ----------

-- MAGIC %sh
-- MAGIC cp /Volumes/workspace/ecommerce/ecommerce_data/2019-Nov.csv /Volumes/workspace/ecommerce/ecommerce_data/Batch/2019-Nov.csv

-- COMMAND ----------


